---
- name: Install Apache (Ubuntu/Debian)
  apt:
    name: apache2
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Install Apache (CentOS/RHEL)
  yum:
    name: httpd
    state: present
  when: ansible_os_family == 'RedHat'


- name: Enable and start Apache (Ubuntu/Debian)
  service:
    name: apache2
    enabled: yes
    state: started
  when: ansible_os_family == 'Debian'

- name: Enable and start Apache (CentOS/RHEL)
  service:
    name: httpd
    enabled: yes
    state: started
  when: ansible_os_family == 'RedHat'


- name: Ensure Apache is running
  uri:
    url: "http://localhost"
    status_code: 200
    timeout: 5
  register: apache_check
  until: apache_check.status == 200
  retries: 3
  delay: 5
  ignore_errors: yes

- name: Set Apache log directory based on OS
  set_fact:
    apache_log_dir: "{{ '/var/log/apache2' if ansible_os_family == 'Debian' else '/var/log/httpd' }}"

- name: Deploy virtual host config
  template:
    src: vhost.conf.j2
    dest: "/etc/apache2/sites-available/{{ domain_name }}.conf"
    owner: root
    group: root
    mode: '0644'
  notify: Restart Apache
  when:
    - ansible_os_family == 'Debian'
    - domain_name is defined

- name: Allow HTTP (Ubuntu)
  ufw:
    rule: allow
    port: "80"
    proto: tcp
  when: ansible_os_family == 'Debian'
