---
- name: Install Fail2Ban (Debian/Ubuntu)
  ansible.builtin.apt:
    name: fail2ban
    state: present
  when: ansible_os_family == 'Debian'

- name: Install Fail2Ban (CentOS/RHEL)
  ansible.builtin.yum:
    name: fail2ban
    state: present
  when: ansible_os_family == 'RedHat'

- name: Deploy Fail2Ban config
  ansible.builtin.template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'
  notify: restart fail2ban
