services:
  vikunja:
    image: vikunja/vikunja
    ports:
      - "3456:3456"
    volumes:
      - ./vikunja-data:/app/vikunja/files
    environment:
      VIKUNJA_DATABASE_TYPE: sqlite
      VIKUNJA_DATABASE_PATH: "/app/vikunja/vikunja.db"
