- name: Deploy radicale docker service
  hosts: radicale
  become: yes

  vars:
    radicale_repo: "{{ playbook_dir }}/../../docker/radicale"  # локальный путь
    radicale_dir: /opt/radicale
    radicale_user: radicale
    restore_backup: true
    backup_file: radicale_backup.tar.gz

  roles:
    - radicale
