- name: Test Playbook
  hosts: all

  vars:
    target_dir: /tmp


  tasks:
    - name: Проверка диска
      ansible.builtin.command:
        cmd: df -h {{ target_dir }}
      register: disk_usage

    - name: Вывод результата
      ansible.builtin.debug:
        var: disk_usage.stdout_lines
