---

- name: Install system dependencies
  apt:
    name:
      - docker.io
      - docker-compose
      - python3-pip
    update_cache: yes
    state: latest


- name: Install Python Docker SDK
  pip:
    name:
      - docker
      - docker-compose
      - requests
    state: present
    extra_args: --break-system-packages


- name: Add current user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  notify: reload docker group


- name: Ensure Joomla directory exists
  file:
    path: "{{ joomla_dir }}"
    state: directory
    mode: '0755'


- name: Deploy docker-compose configuration
  copy:
    src: "files/docker-compose.yml"
    dest: "{{ joomla_dir }}/docker-compose.yml"
    mode: '0644'


- name: Start Joomla services
  community.docker.docker_compose_v2:
    project_src: "{{ joomla_dir }}"
    state: present
    build: never
    recreate: always
    pull: always


- name: Wait for Joomla to become available
  wait_for:
    port: 8080
    delay: 10
    timeout: 300
