---
- name: Ensure Joomla directory exists
  file:
    path: "{{ joomla_dir }}"
    state: directory
    mode: '0755'


- name: Deploy docker-compose configuration
  copy:
    src: "files/docker-compose.yml"
    dest: "{{ joomla_dir }}/docker-compose.yml"
    mode: '0644'


# - name: Start Joomla services
#   community.docker.docker_compose_v2:
#     project_src: "{{ joomla_dir }}"
#     state: present
#     build: never
#     recreate: always
#     pull: always

- name: Start Joomla services with docker-compose
  community.docker.docker_compose:
    project_src: "{{ joomla_dir }}"
    state: present
    build: false
    recreate: always
    pull: yes

- name: Wait for Joomla to become available
  wait_for:
    port: 8080
    delay: 10
    timeout: 300
